-- Create Occupation enum with all values
CREATE TYPE "Occupation" AS ENUM (
  'STUDENT',
  'DEVELOPER',
  'DEVOPS_ENGINEER',
  'DATA_SCIENTIST',
  'DESIGNER',
  'PRODUCT_MANAGER',
  'BUSINESS_OWNER',
  'FINANCE_PROFESSIONAL',
  'HEALTHCARE_PROFESSIONAL',
  'EDUCATOR',
  'ENGINEER',
  'OTHER'
);
