-- Thêm các giá trị mới vào enum Occupation
-- PostgreSQL không cho xóa enum value, chỉ có thể ADD
-- Giá trị cũ (DEVELOPER, DEVOPS_ENGINEER, DATA_SCIENTIST) đã có sẵn trong DB

ALTER TYPE "Occupation" ADD VALUE IF NOT EXISTS 'DEVELOPER';
ALTER TYPE "Occupation" ADD VALUE IF NOT EXISTS 'DEVOPS_ENGINEER';
ALTER TYPE "Occupation" ADD VALUE IF NOT EXISTS 'DATA_SCIENTIST';
ALTER TYPE "Occupation" ADD VALUE IF NOT EXISTS 'DESIGNER';
ALTER TYPE "Occupation" ADD VALUE IF NOT EXISTS 'PRODUCT_MANAGER';
ALTER TYPE "Occupation" ADD VALUE IF NOT EXISTS 'BUSINESS_OWNER';
ALTER TYPE "Occupation" ADD VALUE IF NOT EXISTS 'FINANCE_PROFESSIONAL';
ALTER TYPE "Occupation" ADD VALUE IF NOT EXISTS 'HEALTHCARE_PROFESSIONAL';
ALTER TYPE "Occupation" ADD VALUE IF NOT EXISTS 'EDUCATOR';
ALTER TYPE "Occupation" ADD VALUE IF NOT EXISTS 'ENGINEER';
